# Generated by Django 5.2 on 2026-04-16 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('label', models.CharField(max_length=100, verbose_name='Подпись')),
                ('kind', models.CharField(choices=[('place', 'Место'), ('booking', 'Заявка')], max_length=10, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'constraints': [models.UniqueConstraint(fields=('code', 'kind'), name='uniq_status_code_kind')],
            },
        ),
        migrations.CreateModel(
            name='ComputerPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('zone', models.CharField(max_length=100, verbose_name='Зона')),
                ('operating_system', models.CharField(max_length=100, verbose_name='Операционная система')),
                ('status', models.ForeignKey(limit_choices_to={'kind': 'place'}, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='library_booking.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Компьютерное место',
                'verbose_name_plural': 'Компьютерные места',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (мин.)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='library_booking.computerplace', verbose_name='Место')),
                ('status', models.ForeignKey(limit_choices_to={'kind': 'booking'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='library_booking.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='computerplace',
            constraint=models.UniqueConstraint(fields=('zone', 'number'), name='uniq_zone_number'),
        ),
    ]
